name: Publish Packages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish FYRO.Common.Application
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: src/Application/Application.csproj
          NUGET_KEY: ${{secrets.NUGET_TOKEN}}
    - name: Publish FYRO.Common.Domain
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/Domain/Domain.csproj
          NUGET_KEY: ${{secrets.NUGET_TOKEN}}
    - name: Publish FYRO.Common.Infrastructure
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/Infrastructure/Infrastructure.csproj
          NUGET_KEY: ${{secrets.NUGET_TOKEN}}
    