name: Publish Packages

on:
  push:
    branches: [ main ]

env:
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: 'Get Version'
      id: version
      uses: battila7/get-version-action@v2

    - name: 'Pack project'
      run: dotnet pack src/Application/Application.csproj --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - name: 'Push package'
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}

    - name: Publish FYRO.Application
      uses: alirezanet/publish-nuget@v3.0.0
      with:
          PROJECT_FILE_PATH: src/Application/Application.csproj
          NUGET_KEY: ${{secrets.NUGET_TOKEN}}

    - name: Publish FYRO.Domain
      uses: alirezanet/publish-nuget@v3.0.0
      with:
          PROJECT_FILE_PATH: src/Domain/Domain.csproj
          NUGET_KEY: ${{secrets.NUGET_TOKEN}}

    - name: Publish FYRO.Infrastructure
      uses: brandedoutcast/publish-nuget@v2
      with:
          PROJECT_FILE_PATH: src/Infrastructure/Infrastructure.csproj
          NUGET_KEY: ${{secrets.NUGET_TOKEN}}
    